import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  portalSidebar: [
    "index",
    {
      type: "category",
      label: "Architecture",
      link: { type: "generated-index" },
      items: [{ type: "autogenerated", dirName: "architecture" }],
    },
    {
      type: "category",
      label: "Standards",
      link: { type: "generated-index" },
      items: [{ type: "autogenerated", dirName: "standards" }],
    },
    {
      type: "category",
      label: "Runbooks",
      link: { type: "generated-index" },
      items: [{ type: "autogenerated", dirName: "runbooks" }],
    },
    {
      type: "category",
      label: "ADR",
      link: { type: "generated-index" },
      items: [{ type: "autogenerated", dirName: "adr" }],
    },
    {
      type: "category",
      label: "API Reference",
      link: { type: "generated-index" },
      items: [{ type: "autogenerated", dirName: "api" }],
    },
  ],
};

export default sidebars;
